### ISSUE TITLE
Error with find best tree of population

### ISSUE THREAD

**Issue by BenedettoSimone** [DanieleSalerno/EDTforCSD#3]
After performing genetic operator at each epoch, we have an error when we compute the best tree based on fitness function.

**Comment by DanieleSalerno** [comment]
# I found the method incriminated 
## __mutation

` mutated_population.append(tree)` line 201

**Comment by BenedettoSimone** [comment]
It's a serialization problem. When we insert a new tree into the list and there is already a tree with the same identifier, the new tree is inserted and the tree with the same identifier is replaced with the new tree.

**Comment by BenedettoSimone** [comment]
I addedd deepcopy function in ``crossover`` function at line 189.

Before:
```
first_tree = mating_pool[index_first_tree]
second_tree = mating_pool[index_second_tree]
```

After:
```
first_tree = deepcopy(mating_pool[index_first_tree])
second_tree = deepcopy(mating_pool[index_second_tree])
```
